name: CI

on: push

env:
  region: ${{ env.AWS_REGION }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run hello action
      uses: ./.github/actions/hello-action
      with:
        region: ${{ env.region }}
